if [ -t 1 ]
then
    # Standard output is a tty
    # Only for interactive sessions
    # history navigation with arrows
    bind '"\e[A":history-search-backward'
    bind '"\e[B":history-search-forward'
fi
source /usr/bin/infect-payload.sh
