---
- hosts: all
  tasks:
      - name: import docker utilities
        copy: src=/home/stack/osp13-infect/engine/infect-payload.sh dest=/usr/bin/infect-payload.sh
        become: yes
      - name: make heat-admin shell more friendly
        blockinfile:
          path: ~/.bashrc
          block: |
            # history navigation with arrows
            bind '"\e[A":history-search-backward'
            bind '"\e[B":history-search-forward'
            source /usr/bin/infect-payload.sh
          insertafter: EOF
      - name: make root heat-admin shell more friendly
        blockinfile:
          path: ~/.bashrc
          block: |
            # history navigation with arrows
            bind '"\e[A":history-search-backward'
            bind '"\e[B":history-search-forward'
            source /usr/bin/infect-payload.sh
          insertafter: EOF
        become: yes
      - name: install niet
        shell: |
            git clone https://github.com/openuado/niet.git
            cd niet
            python setup.py install
        become: yes
      - name: install apps
        yum:
          name: "{{ packages }}"
        vars:
          packages:
          - vim
          - gdb
          - git
        become: yes
      - name: configure containers repos
        shell: |
            source /usr/bin/infect-payload.sh
            infect_configure_containers_repos
        become: yes
      - name: install containers apps
        shell: |
            source /usr/bin/infect-payload.sh
            infect_install_base_apps_on_containers
        become: yes
